# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_SENSOR=y
CONFIG_BLINK=y
CONFIG_MOTOR=y

CONFIG_LOG=y
# CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
# CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y
# CONFIG_USB_DEVICE_GS_USB_LOG_LEVEL_DBG=y
# CONFIG_CANNECTIVITY_LOG_LEVEL_DBG=y

# CONFIG_USB_DEVICE_STACK=y
# CONFIG_USB_DEVICE_BOS=y
# CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n

CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y
CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y

CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP17=y
