CONFIG_DEPRECATION_TEST=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_BOS=y
CONFIG_USB_COMPOSITE_DEVICE=y

CONFIG_USB_DEVICE_MANUFACTURER="Fibril"
CONFIG_USB_DEVICE_PRODUCT="RoboMaster Mini V1"
CONFIG_USB_DEVICE_GS_USB_MAX_CHANNELS=1

CONFIG_ISR_TABLES_LOCAL_DECLARATION=n
CONFIG_LTO=n
